name: CI

on:
  push:
  pull_request:

env:
  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COVERAGE: '0'
  SYMFONY_DEPRECATIONS_HELPER: disabled=1

jobs:
  elasticsearch:
    name: Behat (PHP ${{ matrix.php }}) (Elasticsearch)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        php:
          - '8.0'
          - '8.1'
        elasticsearch:
          - '7.6.0'
          - '8.5.0'
      fail-fast: false
    env:
      APP_ENV: elasticsearch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: ${{ matrix.elasticsearch }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl, composer
          extensions: intl, bcmath, curl, openssl, mbstring, mongodb
          coverage: none
          ini-values: memory_limit=-1
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Update project dependencies
        run: composer update --no-interaction --no-progress --ansi
      - name: Require Symfony components
        run: composer require symfony/uid --dev --no-interaction --no-progress --ansi
      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit --version
      - name: Clear test app cache
        run: tests/Fixtures/app/console cache:clear --ansi
      - name: Run Behat tests
        run: vendor/bin/behat --out=std --format=progress --profile=elasticsearch --no-interaction
